### ISSUE TITLE
Option for Pump Events

### ISSUE THREAD

**Issue by ryanchen26** [jwoglom/tconnectsync-heroku#3]
Currently I have 2 instances of this working great on Heroku. Great work!  Would it be possible to add pump events as an option for upload to Nightscout? I see how you did it in the main tconnectsync project but the heroku version doesn't have all the folders that the main tconnect version has...so the features are locked currently? Thanks again.

**Comment by jwoglom** [comment]
Hi Ryan,

Great observation -- this is just an oversight rather than any sort of architectural incompatibility. I will add the option in.

**Comment by jwoglom** [comment]
Resolved in https://github.com/jwoglom/tconnectsync-heroku/commit/b96a56b127f87a278756010c60ec54504458c4c3

**Comment by ryanchen26** [comment]
Hello again! Thanks for the quick response. I tested it throughout the day and was unable to get the pump events that I am able to see on NS if I run the tconnectsync code locally on a PC. See attached images. I also tried just setting features = ALL_FEATURES in the util.py file but that prevented the process from running entirely. I'm mainly interested in this because I have 2 T1D boys in elementary school and if we could get to a point where if an occlusion alarm happens at school, and the event posts to Nightscout, and then I can just add a corresponding alarm to my Sentinel watch project, that would be awesome.  I'll add that I tried to get the patcher to work and had no luck with that..so far. Not sure how many android devices you tested it on, or if there are some compatibility issues with certain versions of Android...but spent some time on it digging around. Those APK download sites feel really shady. The file sizes are different...not sure what to make of it.  Despite all that, what you've provided is a real step up. Good job!

![Screenshot_tconnectsync_heroku_with_pump_events](https://user-images.githubusercontent.com/16513711/148670597-85021bd7-eaf8-4109-8c23-e858ea91a03a.jpg)
![Screenshot_tconnectsync_with_pump_events_working](https://user-images.githubusercontent.com/16513711/148670599-df7c67fa-be34-478d-a5a0-fae59f9e26ae.jpg)
![Screenshot heroku_config_vars_features](https://user-images.githubusercontent.com/16513711/148670616-d4766075-853f-4de6-bd0d-bf994c458101.jpg)

**Comment by jwoglom** [comment]
If you haven't yet, make sure you go through the updating instructions in the readme since I added the proper code to read from that environment variable only yesterday.

For tconnectpatcher, If it helps, here are the apk's I've used: https://github.com/jwoglom/tconnectapks

**Comment by ryanchen26** [comment]
That does help. Had to manually modify the unpacked apk v1.2 on my PC, but it ultimately worked. Also deleted and re-established the tconnectsync_heroku apps, so it should display pump events given your recent updates. We were thinking of testing an occlusion alarm just to see if it works and how/where the alarms are logged...later today. Thanks.

**Comment by ryanchen26** [comment]
I'm fairly certain that pump events still don't work with the the tconnectsync_heroku implementation. Just FYI, no pressure. I did a clean install of the latest and it didn't register a clear site change. But if you run the main tconnectsync it works. Something to ponder, take a look when you have free time. Just seeing the auto boluses is a big deal as-is. Also do we know if pump alarms are registered and transmitted as notes to nightscout? I re-read your Readme info and didn't see mention of alarms.

**Comment by gte731v** [comment]
I'm experiencing the same behavior where the PUMP_EVENTS work when running via Windows command and not the Heroku version.  Wish I knew more than basic python to help debug.  Not an issue for me as I can just revert back to the windows job.  Thanks again for developing this awesome tool!
